networks:
    bettime:    
        driver: bridge  

volumes:
    db-data:
 
services:
    db:
        image: mcr.microsoft.com/mssql/server:2019-CU21-ubuntu-20.04
        restart: always
        ports:
            - 8118:1433
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=Kira1234@1234
        networks:
            - bettime
        volumes:
            - db-data:/var/opt/mssql    
    api:
        restart: unless-stopped 
        ports:
            - 7118:80 
        build:
          context: .
          dockerfile: BetTime.API/Dockerfile
        depends_on:
            - db
        networks:
            - bettime
        